#!/usr/bin/env bash
# Script Configuring Ubuntu server to some custom HAproxy load-balancer.
sudo apt-get update
sudo apt-get install haproxy -y
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http-in
        bind *:80
        default_backend servers


backend servers
        balance roundrobin
        server web-01 18.207.234.171:80 check
        server web-02 35.153.226.243:80 check
EOT

sudo /etc/init.d/haproxy start
sudo update-rc.d haproxy defaults
sudo /etc/init.d/haproxy reload
