#!/usr/bin/env bash
# Script Configuring Ubuntu server to some custom HAproxy load-balancer.
sudo apt-get update
sudo apt-get install haproxy -y

# Configure HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http-in
        bind *:80
        default_backend servers


backend servers
        balance roundrobin
        server web-01 35.153.79.141:80 check
        server web-02 54.144.136.126:80 check
EOT

# start HAProxy
sudo /etc/init.d/haproxy start

# set HAProxy to start on boot
sudo update-rc.d haproxy defaults

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
