#!/usr/bin/env bash
#Script that configures an nginx server.

sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
