#!/usr/bin/env bash
# Prints To infinity and beyond
# Prints Y U no love me?! when receiving a SIGINT signal
# Creates file containing PID
# Deletes file and terminates itself
# Prints kill command when receiving a SIGTERM signal

true=0
echo $BASHPID > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm /var/run/myscript.pid; exit 0;' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/myscript.pid; exit 0;' SIGQUIT
while [ $true ]; do
	echo 'To infinity and beyond'
	sleep 2
done;
